app:
  minio:
    enable: false
  security:
    whitelist:
      - /favicon.ico
      - /**
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/ueditor
      - /app/files
      - /app/files/**
      - /app/minio/upload
  jwt:
    secret: 123456

spring:
  profiles:
    active: local
  # 输出带有颜色的控制台日志
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

# todo 这个配置是干什么的
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  level:
    root: DEBUG
    org.apache.coyote.http11: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.security: debug
