spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clever_framework_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQL55Dialect #使用innodb引擎
        format_sql: true
        enable_lazy_load_no_trans: true
  data:
    rest:
      defaultMediaType: application/json
#    hibernate:
#      ddl-auto: create-drop
  hateoas:
    use-hal-as-default-json-media-type: true


logging:
  level:
    root: info
    org.springframework.security: debug
    io.github.toquery.framework: debug
    io.github.toquery.framework.security: debug
    com.toquery: debug

mybatis:
  # 匹配多个包，下指定路径的多个xml文件
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

server:
  port: 8888
app:
  minio:
    enable: true
    access-key: admin
    secret-key: admin123
    endpoint: http://127.0.0.1:9000/
    port: 9000

