app:
  security:
    whitelist:
      - /favicon.ico
      - /**
      - /index.html
      - /static/**
      - /error
      - /h2-console/**
      - /app/ueditor
      - /app/files
      - /app/files/**
  jwt:
    secret: 123456

spring:
  profiles:
    active: dev
  # 输出带有颜色的控制台日志
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

# todo 这个配置是干什么的
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: DEBUG
    org:
      apache:
        coyote:
          http11: debug
      springframework:
        security: debug