app:
  page:
    param:
      page-size: ps

  security:
    whitelist:
      - /**

spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

# todo 这个配置是干什么的
  main:
    allow-bean-definition-overriding: true